export const PRODUCTS = [
  { id: 'shadow-hoodie', name: 'SHADOW HOODIE', price: 1250000, priceDisplay: 'IDR 1.250.000', image: '/images/product-hoodie.png', category: 'Tops', sku: 'SNK-HD-001', material: '100% Premium Cotton Fleece', isNew: true, desc: 'The Shadow Hoodie defines the SHINKO silhouette — oversized, heavy-weight, and built for the streets. Features a relaxed drop-shoulder cut, ribbed cuffs, and tonal embroidered branding.' },
  { id: 'core-tee', name: 'CORE TEE', price: 450000, priceDisplay: 'IDR 450.000', image: '/images/product-tshirt.png', category: 'Tops', sku: 'SNK-TE-002', material: '220gsm Combed Cotton', isNew: true, desc: 'A wardrobe essential elevated. The Core Tee features a boxy fit, reinforced neck ribbing, and a subtle SHINKO woven label. Designed for layering or standalone wear.' },
  { id: 'tactical-cargo', name: 'TACTICAL CARGO', price: 980000, priceDisplay: 'IDR 980.000', image: '/images/product-cargo.png', category: 'Bottoms', sku: 'SNK-CG-003', material: 'Ripstop Nylon Blend', isNew: true, desc: 'Functional meets fashion. The Tactical Cargo features multi-pocket utility design, adjustable ankle cuffs, and a relaxed tapered fit that moves with you.' },
  { id: 'noir-bomber', name: 'NOIR BOMBER', price: 1680000, priceDisplay: 'IDR 1.680.000', image: '/images/product-bomber.png', category: 'Outerwear', sku: 'SNK-BM-004', material: 'Heavyweight Nylon Shell, Satin Lining', isNew: true, desc: 'The Noir Bomber is a SHINKO icon — minimal, powerful, timeless. Crafted with a structured shell, custom ribbed trim, and an interior satin finish.' },
  { id: 'core-cap', name: 'CORE CAP', price: 320000, priceDisplay: 'IDR 320.000', image: '/images/product-cap.png', category: 'Accessories', sku: 'SNK-CP-005', material: 'Structured Canvas', isNew: true, desc: 'The Core Cap completes the look. Features an embroidered SHINKO logo on the front panel, adjustable metal clasp closure, and pre-curved visor.' },
  { id: 'tactical-sling', name: 'TACTICAL SLING', price: 580000, priceDisplay: 'IDR 580.000', image: '/images/product-bag.png', category: 'Accessories', sku: 'SNK-BG-006', material: 'Ballistic Nylon', isNew: true, desc: 'Built for movement. The Tactical Sling features a padded crossbody strap, multiple zip compartments, and a magnetic front flap with SHINKO branding.' },
  { id: 'midnight-hoodie', name: 'MIDNIGHT HOODIE', price: 1350000, priceDisplay: 'IDR 1.350.000', image: '/images/product-midnight-hoodie.png', category: 'Tops', sku: 'SNK-HD-007', material: '100% Premium Cotton Fleece', isNew: false, desc: 'The Midnight Hoodie — a darker take on the SHINKO silhouette. Features an all-black construction with tonal embroidery and kangaroo pocket.' },
  { id: 'street-tee', name: 'STREET TEE', price: 480000, priceDisplay: 'IDR 480.000', image: '/images/product-street-tee.png', category: 'Tops', sku: 'SNK-TE-008', material: '220gsm Combed Cotton', isNew: false, desc: 'The Street Tee features a bold back graphic with the SHINKO manifesto. Boxy cut, drop shoulder, and premium feel.' },
  { id: 'stealth-jogger', name: 'STEALTH JOGGER', price: 850000, priceDisplay: 'IDR 850.000', image: '/images/product-jogger.png', category: 'Bottoms', sku: 'SNK-JG-009', material: 'French Terry Cotton Blend', isNew: false, desc: 'The Stealth Jogger merges comfort with edge. Tapered silhouette with hidden zip pockets, elastic cuffs, and a drawstring waist for the perfect fit.' },
  { id: 'phantom-jacket', name: 'PHANTOM JACKET', price: 1980000, priceDisplay: 'IDR 1.980.000', image: '/images/product-jacket.png', category: 'Outerwear', sku: 'SNK-JK-010', material: 'Water-Resistant Nylon, Mesh Lining', isNew: false, desc: 'The Phantom Jacket is engineered for the city. Lightweight, water-resistant shell with taped seams, concealed hood, and reflective SHINKO hit on the back.' },
  { id: 'essential-longsleeve', name: 'ESSENTIAL LONGSLEEVE', price: 520000, priceDisplay: 'IDR 520.000', image: '/images/product-longsleeve.png', category: 'Tops', sku: 'SNK-LS-011', material: '200gsm Combed Cotton Jersey', isNew: false, desc: 'A layering staple. The Essential Longsleeve features a relaxed fit, extended cuffs with thumb holes, and subtle embroidered branding at the chest.' },
  { id: 'urban-beanie', name: 'URBAN BEANIE', price: 280000, priceDisplay: 'IDR 280.000', image: '/images/product-beanie.png', category: 'Accessories', sku: 'SNK-BN-012', material: 'Ribbed Acrylic Knit', isNew: false, desc: 'The Urban Beanie is a cold-weather essential. Double-fold construction with woven SHINKO label. One size fits all.' },
  { id: 'cargo-shorts', name: 'CARGO SHORTS', price: 720000, priceDisplay: 'IDR 720.000', image: '/images/product-shorts.png', category: 'Bottoms', sku: 'SNK-SH-013', material: 'Ripstop Cotton Blend', isNew: false, desc: 'Summer-ready utility. The Cargo Shorts feature oversized pockets, a relaxed cut above the knee, and an adjustable belt loop system.' },
  { id: 'oversized-tee-v2', name: 'OVERSIZED TEE V2', price: 480000, priceDisplay: 'IDR 480.000', image: '/images/product-oversized-tee.png', category: 'Tops', sku: 'SNK-TE-014', material: '250gsm Heavyweight Cotton', isNew: false, desc: 'The V2 takes our oversized tee to the next level. Heavier weight, wider cut, and a raw-edge neckline for that deconstructed look.' },
  { id: 'crossbody-bag', name: 'CROSSBODY BAG', price: 650000, priceDisplay: 'IDR 650.000', image: '/images/product-crossbody.png', category: 'Accessories', sku: 'SNK-CB-015', material: '1000D Cordura Nylon', isNew: false, desc: 'Ultra-durable and minimal. The Crossbody Bag features a single-zip main compartment, internal organizer, and quick-release buckle strap.' },
  { id: 'shadow-hoodie-v2', name: 'SHADOW HOODIE V2', price: 1380000, priceDisplay: 'IDR 1.380.000', image: '/images/product-hoodie-v2.png', category: 'Tops', sku: 'SNK-HD-016', material: '400gsm Heavyweight Cotton Fleece', isNew: false, desc: 'The evolution. Shadow Hoodie V2 features double-layered hood construction, oversized metal eyelets, and a reinforced kangaroo pocket with hidden zip.' },
  { id: 'utility-vest', name: 'UTILITY VEST', price: 1150000, priceDisplay: 'IDR 1.150.000', image: '/images/product-vest.png', category: 'Outerwear', sku: 'SNK-VT-017', material: 'Quilted Nylon Shell', isNew: false, desc: 'Layer up. The Utility Vest features quilted padding, multiple front pockets, and a stand collar. Designed for transitional weather.' },
  { id: 'stealth-cap', name: 'STEALTH CAP', price: 350000, priceDisplay: 'IDR 350.000', image: '/images/product-stealth-cap.png', category: 'Accessories', sku: 'SNK-CP-018', material: 'Waxed Canvas', isNew: false, desc: 'Water-resistant waxed canvas cap with debossed SHINKO logo. Weathered finish for that lived-in look. Adjustable leather strap closure.' },
  { id: 'tech-pants', name: 'TECH PANTS', price: 1080000, priceDisplay: 'IDR 1.080.000', image: '/images/product-tech-pants.png', category: 'Bottoms', sku: 'SNK-TP-019', material: '4-Way Stretch Nylon', isNew: false, desc: 'Performance meets street. The Tech Pants feature articulated knees, zippered calf openings, and a water-resistant DWR finish for all-weather wear.' },
  { id: 'graphic-tee-rebellion', name: 'GRAPHIC TEE — REBELLION', price: 520000, priceDisplay: 'IDR 520.000', image: '/images/product-graphic-tee.png', category: 'Tops', sku: 'SNK-GT-020', material: '220gsm Combed Cotton', isNew: false, desc: 'Featuring the "REBELLION" graphic — a large-scale screen print across the back. Front left chest features a small SHINKO emblem. Boxy oversized fit.' }
];

export const LOOKBOOK_CHAPTERS = [
  { id: 'urban-identity', chapter: '01', title: 'URBAN IDENTITY', subtitle: 'SS26 — CHAPTER 01', heroImage: '/images/lookbook-1.png', description: 'The city is our canvas. Urban Identity captures the raw energy of street culture — from dimly lit alleyways to rooftop silhouettes. This chapter explores how SHINKO pieces become extensions of personality in the urban landscape.', images: ['/images/lookbook-1.png', '/images/product-hoodie.png', '/images/product-bomber.png', '/images/hero.png'], credits: 'Photography by SHINKO Creative Studio. Shot on location in Jakarta.' },
  { id: 'shadow-series', chapter: '02', title: 'SHADOW SERIES', subtitle: 'SS26 — CHAPTER 02', heroImage: '/images/lookbook-2.png', description: 'When light fades, identity sharpens. The Shadow Series is an exploration of darkness as a design principle — monochromatic tones, muted textures, and silhouettes that speak louder than color ever could.', images: ['/images/lookbook-2.png', '/images/product-tshirt.png', '/images/product-cargo.png', '/images/brand-story-bg.png'], credits: 'Photography by SHINKO Creative Studio. Post-production by Studio Noir.' },
  { id: 'night-protocol', chapter: '03', title: 'NIGHT PROTOCOL', subtitle: 'SS26 — CHAPTER 03', heroImage: '/images/lookbook-3.png', description: 'The night belongs to those who refuse to rest. Night Protocol documents the after-hours energy — neon reflections, empty streets, and the quiet confidence of those who own the night.', images: ['/images/lookbook-3.png', '/images/product-bag.png', '/images/product-cap.png', '/images/lookbook-1.png'], credits: 'Photography by SHINKO Creative Studio. Night session, Jakarta District 9.' },
  { id: 'street-culture', chapter: '04', title: 'STREET CULTURE', subtitle: 'SS26 — CHAPTER 04', heroImage: '/images/brand-story-bg.png', description: 'Culture is not consumed — it is lived. Street Culture captures the intersection of fashion, music, and movement. From skateparks to underground shows, SHINKO lives where culture breathes.', images: ['/images/brand-story-bg.png', '/images/product-hoodie.png', '/images/lookbook-2.png', '/images/product-tshirt.png'], credits: 'Photography by SHINKO Creative Studio. Community collaboration.' },
  { id: 'the-campaign', chapter: '05', title: 'THE CAMPAIGN', subtitle: 'SS26 — CHAPTER 05', heroImage: '/images/hero.png', description: 'The SS26 Campaign is our definitive statement. Shot across three cities over two weeks, this chapter brings together every element of the SHINKO vision — identity, darkness, culture, and the relentless pursuit of authenticity.', images: ['/images/hero.png', '/images/lookbook-3.png', '/images/product-bomber.png', '/images/lookbook-1.png'], credits: 'Photography by SHINKO Creative Studio. SS26 Global Campaign.' },
  { id: 'identity-redefined', chapter: '06', title: 'IDENTITY REDEFINED', subtitle: 'SS26 — CHAPTER 06', heroImage: '/images/lookbook-1.png', description: 'Who you are is not fixed — it evolves. Identity Redefined closes the SS26 story with a challenge: break your own rules, reinvent your style, and let your identity be a living, breathing thing.', images: ['/images/lookbook-1.png', '/images/hero.png', '/images/brand-story-bg.png', '/images/lookbook-3.png'], credits: 'Photography by SHINKO Creative Studio. Final chapter, SS26.' }
];
